class _BotCommands:
    def __init__(self):
        self.LeechCommand = 'leech'
        self.gLeechCommand = 'gleech'
        self.ExtractCommand = 'leechunzip'
        self.gExtractCommand = 'gleechunzip'
        self.ArchiveCommand = 'zipleech'
        self.gArchiveCommand = 'gzipleech'
        self.telegramfleechCommand = 'tleech'
        self.telegramexleechCommand = 'tleechunzip'
        self.gcloneCommand = 'gclone'
        self.YtdlCommand = 'ytdl'
        self.gYtdlCommand = 'gytdl'
        self.PytdlCommand = 'pytdl'
        self.gPytdlCommand = 'pytdl'        
        self.ToggleDocCommand = 'toggledoc'
        self.ToggleVidCommand = 'togglevid'
        self.SaveCommand = 'savethumb'
        self.ClearCommand = 'clearthumb'
        self.RenameCommand = 'rename'
        self.StatusCommand = 'status'
        self.SpeedCommand = 'speedtest'
        self.HelpCommand = 'help'
        self.LogCommand = 'log'
        self.TsHelpCommand = 'tshelp'

BotCommands = _BotCommands()
